version: "3.8"

volumes:
  var:
  db-data:
  code:

networks:
  docker-symfony:

services:

  database:
    container_name: mariadb
    image: mariadb:10-bionic
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
    volumes:
      - db-data:/var/lib/mysql:rw
    networks:
      - docker-symfony
    ports:
      - 3306:3306

  app:
    container_name: php-fpm
    image: symfony-php-fpm
    restart: on-failure
    build:
      context: .
      target: app_php
      dockerfile: .docker/Dockerfile
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    ports:
      - 9000:9000
    volumes:
      - .:/var/www
      - var:/var/www/var:rw
    depends_on:
      - database
    networks:
      - docker-symfony

  server:
    container_name: nginx
    image: nginx:1.21.0-alpine
    restart: on-failure
    build:
      context: .
      target: app_nginx
      dockerfile: .docker/Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./public:/var/www/public:ro
    depends_on:
      - app
    networks:
      - docker-symfony
